[package]
name = "controller-tools"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.1"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.3.0", features = ["cors"] }
hidapi = "2.1.0"
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
udev = "^0.7.0"
#evdev = "^0.12.1"
#evdev-rs = "^0.6.1"

# logging
log = "0.4"
simplelog = "0.12"